[package]
name = "capacitor_bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_with = "2.2.0"
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = "0.4"

[dev-dependencies]
serde_test = "1"
serde_json = "1"

[features]
web =[]
android = []
ios = []